[uwsgi]

http = 0.0.0.0:80
chmod-socket = 666
gevent = 1000
http-websockets = true
master = true
wsgi-file = run.py
callable = app
enable-threads = true
single-interpreter = true
lazy = true
disable-logging = true
py-autoreload = 1

