[uwsgi]

wsgi-file = start.py
callable = app

http = 0.0.0.0:5000
# https = =0,selfsigned.crt,selfsigned.key,HIGH
# http-to-https = =0

protocol = uwsgi

# uid = www-data
# gid = www-data

# shared-socket = project.sock
# socket = project.sock
chmod-socket = 666
# buffer-size=32768

gevent = 1000
http-websockets = true

master = true

enable-threads = true
single-interpreter = true
lazy = true

disable-logging = true

die-on-term = true
vacuum = true

# workers = 2
# processes = 4

# py-autoreload = 1

# max-requests = 1000                  ; Restart workers after this many requests
# max-worker-lifetime = 3600           ; Restart workers after this many seconds
# reload-on-rss = 2048                 ; Restart workers after this much resident memory
# worker-reload-mercy = 60             ; How long to wait before forcefully killing workers
