[ignore: venv/**]
[ignore: .idea/**]
[ignore: .vscode/**]
[ignore: **/__pycache__/**]
[python: *.py]
[python: **/library/**.py]
[jinja2: **/templates/**.html]
extensions=jinja2.ext.i18n,jinja2.ext.autoescape,jinja2.ext.with_
[javascript:**/static/js/*.js]
encoding = utf-8
extract_messages=_,gettext,ngettext
