# Blacklist config

[default]
# Allow blacklist
state = off
# Allow automatic adding devices to blacklist (when someone is hacking, ...)
auto_add = yes
# Allow automatic removing devices from blacklist (after end_time expires)
auto_remove = yes


[device0]
mac = 9c:e6:5e:bb:8d:61
ip = 192.168.0.101
browser = chrome
browser_version = v81.0.4044.138
browser_language = cs
operating_system = Linux x86_64
reason = Too many login times
start_time = 2020-04-05 04:51:21.04832
end_time = 2020-08-05 04:51:21.04832
