[default]
# Can application start?
run = yes

# Allow registrations
registrations = yes
# Show introduction screen if the user is new there
introduction = yes

# TODO [android] config - app; when connect other app, ...

[refresh]
# Save information before browser refresh (current slide, modal, ..) and then send them back
save = yes
# Time to save these information
time = 15

# Image manager settings
[imng]
# Reclassify on start
reclassify = no
# TODO ultra dark?
limit-ultra-dark = 20
limit-dark = 60

# Set geographic position of current location
[position]
latitude = 49.638994
longitude = 17.148784

# Set log priorities
[logs]
werkzeug_priority = 1
console_priority = 0
auth_priority = 0

# Make validations?
# TODO - some validations may not work
[validation]
json = yes
js = no
html = no
css = no
