# Whitelist config

[default]
# Allow whitelist
state = on
# Allow automatic removing devices from whitelist (after end_time expires)
auto_remove = yes

# Minimal information example:
# [device0]
# mac = 9c:e6:5e:bb:8d:61

# Maximal information example:
# [device1]
# mac = 9c:e6:5e:bb:8d:61
# start_time = 2020-04-05 04:51:21.04832
# end_time = 2020-08-05 04:51:21.04832

[device0]
mac = 9c:e6:5e:bb:8d:61
start_time = 2020-04-05 04:51:21.04832
end_time = 2020-08-05 04:51:21.04832